apiVersion: apps/v1
kind: Deployment
metadata:
  name: multimodal-feedback-backend
  labels:
    app: multimodal-feedback-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multimodal-feedback-backend
  template:
    metadata:
      labels:
        app: multimodal-feedback-backend
    spec:
      containers:
      - name: backend
        image: multimodal-feedback-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "sqlite:///./feedback.db"
        - name: MODEL_PATH
          value: "/app/models"
        volumeMounts:
        - name: models-volume
          mountPath: /app/models
        - name: data-volume
          mountPath: /app/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: models-volume
        persistentVolumeClaim:
          claimName: models-pvc
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: multimodal-feedback-backend-service
spec:
  selector:
    app: multimodal-feedback-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP